### ISSUE TITLE
Poddycast-linux-x64 Dark mode didn't work

### ISSUE THREAD

**Issue by phellipeandrade** [MrChuckomo/poddycast#27]
**System**: Ubuntu 18.04

##### Details
I clicked on *View > Dark Mode*

##### Console Error
```javascript
dark_mode.js:18 Uncaught TypeError: Cannot read property 'checked' of null
    at darkMode (dark_mode.js:18)
    at click (/home/phellipe/Downloads/Poddycast-linux-x64/resources/app.asar/menu.js:30)
    at CallbacksRegistry.apply (/home/phellipe/Downloads/Poddycast-linux-x64/resources/electron.asar/common/api/callbacks-registry.…:48)
    at EventEmitter.<anonymous> (/home/phellipe/Downloads/Poddycast-linux-x64/resources/electron.asar/renderer/api/remote.js:299)
    at emitThree (events.js:116)
    at EventEmitter.emit (events.js:197)
```

**Comment by JosephSamela** [comment]
I was able to replicate this on `Ubuntu 18.04`. Dark Mode toggle didn't seem to do anything as described. Cracked open the debugger and fixed it by editing line `5` of `dark_mode.js` from this:

```javascript
var ViewMenuItem = app.getApplicationMenu().items[2].submenu 
```
to 
```javascript
var ViewMenuItem = app.getApplicationMenu().items[1].submenu 
```
![screenshot from 2018-04-23 20-52-27](https://user-images.githubusercontent.com/16111451/39160270-50bfeaaa-4738-11e8-8c8b-a91d63c2bed0.png)

Notice in this screenshot the application has no `File` menu. I assume this menu appears in other OS's making the `View` menu `items[2]` instead of `items[1]`.

![screenshot from 2018-04-23 21-24-18](https://user-images.githubusercontent.com/16111451/39161055-c76e7b68-473c-11e8-91bc-15d105c38e09.png)

If the `File` menu is unused on Linux, reworking the `darkMode()` function in `dark_mode.js` to include an `isLinux()` case solves this bug.

```javascript
function darkMode()
{
    const {app} = require('electron').remote

    var ViewMenuItem = app.getApplicationMenu().items[2].submenu

    if(isWindows())
    {
        ViewMenuItem = app.getApplicationMenu().items[1].submenu
    } 
    else if(isLinux())
    {
        ViewMenuItem = app.getApplicationMenu().items[1].submenu
    }

    var DarkModeMenu = getDarkModeMenuItem(ViewMenuItem);
```
If the `File` menu is unused remove all cases and use `items[1]`.

@MrChuckomo does the `File` menu appear in MacOS or Windows?

**Comment by MrChuckomo** [comment]
@JosephSamela Thanks for finding this. I'll put this into the next release.

<img width="369" alt="bildschirmfoto 2018-04-24 um 19 21 57" src="https://user-images.githubusercontent.com/29462476/39203440-1155705c-47f5-11e8-81f4-390d66e470f1.png">

Actually there is no `File` menu at all. But there is the App name menu item `Poddycast` on macOS that counts.

**Comment by MrChuckomo** [comment]
@phellipeandrade please try the latest release (v0.6.0). The Dark Mode issue should be fixed now.
