### ISSUE TITLE
Option to test status of saved podcast URL

### ISSUE THREAD

**Issue by alexdevero** [MrChuckomo/poddycast#73]
Sometimes there is a change in some podcast. The name, the artwork, the URL, etc. might change. This can lead to podcast no longer working and syncing. There is now no option to check, or see, which podcasts (URLs) are working and able to sync. Now, user has to open each podcast in "Favorites" and check if the feed with episodes loads or not.

It would be nice to have some way to check either if all podcasts, or specific podcast, work. Some indicator, like a red/green dot would be also useful. User would immediately know that some podcasts are unreachable, and potentially broken.

@MrChuckomo What do you think?

**Comment by MrChuckomo** [comment]
Yes, that's indeed a **must have**! Podcasts URLs can change quite often - that's a problem. Checking the status of Podcast is a nice enhancement.

The check could happen in the background (and shouldn't take too much of the performance). I also think it's not necessary to check too often - maybe once a day?

**Comment by alexdevero** [comment]
Once a day seems reasonable. Maybe adding new prop with time stamp to the item in json with favorite podcasts after every check?

**Comment by MrChuckomo** [comment]
Yes I agree. Timestamp sounds good. 

First I was thinking about putting it into the `...-podcast_setting.json` instead of the `...-favorite_podcasts.json`. 

❓Then the status-refresh can be reflected as kind of setting in the app (later, if necessary)?
❗But actually I think we might can eliminate the `...-podcast_setting.json` file and merge it into the `...-favorite_podcasts.json`. The only real settings property is `addToInbox`. 

👍 So it's good idea to **put the timestamp into the `...-favorite_podcasts.json` file** - if it will contain any podcast related settings anyways later. 

**New issue**

As a side product I'll create a new issue for merging the `...-podcast_setting.json` data into the `...-favorite_podcasts.json` file. #74
