### ISSUE TITLE
Podcasts found, favourited, but epsiodes not identified

### ISSUE THREAD

**Issue by umbellipher** [MrChuckomo/poddycast#87]
A couple of podcasts are found. I favourite them. But no episodes are identified.

See images: 
![Screenshot - 07_06_2021 , 11_21_59](https://user-images.githubusercontent.com/59395777/120992978-05f85e00-c77b-11eb-95d2-37de90ca04ae.png)

Windows 10 Pro build 19041. x64 app version. Always-on VPN. Proxy mode not used.

Looking good - saves me disk space - but see bug above.

**Comment by MrChuckomo** [comment]
@umbellipher thanks for the input. I checked on my side and I can confirm the issue. 
Looks like a general issue with parsing the RSS feeds for some Podcasts. I will check!

**Comment by umbellipher** [comment]
Thanks. "Dan Snow's History Hits" also suffers from this, I see. Both instances which a search brings up. So it's not one podcast provider.

**Comment by EthanGrahn** [comment]
@MrChuckomo I've explored this issue on my end and was able to find a fix using the `makeFeedRssRequest` instead of `makeFeedRequest`. It will require a bit of reconfiguring to make sure every feature works, but could be fully switched over. I'd be willing to work on that after my current pull request is wrapped up!

**Comment by MrChuckomo** [comment]
@EthanGrahn, that sounds really great. I would be very happy if you would like to take a look at it.
